#
# Copyright (c) 2022, MediaTek Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

NAMESPACE := MT7988

ifeq (${CONFIG_${NAMESPACE}_FPGA_SKIP_DRAM},y)
MAKE_ARGS += FPGA_DRAM_TYPE=0
endif

ifeq (${CONFIG_${NAMESPACE}_FPGA_DDR2_256M},y)
MAKE_ARGS += FPGA_DRAM_TYPE=1
endif

ifeq (${CONFIG_${NAMESPACE}_FPGA_DDR2_512M},y)
MAKE_ARGS += FPGA_DRAM_TYPE=2
endif

ifeq (${CONFIG_${NAMESPACE}_FPGA_DDR4},y)
MAKE_ARGS += FPGA_DRAM_TYPE=3
endif

ifeq (${CONFIG_${NAMESPACE}_FPGA_DDR4_8GB},y)
MAKE_ARGS += FPGA_DRAM_TYPE=4
endif

ifeq (${CONFIG_${NAMESPACE}_DRAM_DDR3},y)
MAKE_ARGS += DRAM_USE_DDR4=0
endif

ifeq (${CONFIG_${NAMESPACE}_DRAM_DDR4},y)
MAKE_ARGS += DRAM_USE_DDR4=1
endif

ifeq (${CONFIG_${NAMESPACE}_DRAM_COMB},y)
MAKE_ARGS += DRAM_USE_COMB=1
else
MAKE_ARGS += DRAM_USE_COMB=0
endif

ifneq ($(findstring ${CONFIG_${NAMESPACE}_DRAM_SIZE_8GB}${CONFIG_${NAMESPACE}_DRAM_SIZE_4GB},y y),)
MAKE_ARGS += DDR4_4BG_MODE=1
else
MAKE_ARGS += DDR4_4BG_MODE=0
endif

ifeq (${CONFIG_${NAMESPACE}_DRAM_SIZE_AUTO},y)
endif

ifeq (${CONFIG_${NAMESPACE}_DRAM_SIZE_256},y)
MAKE_ARGS += DRAM_SIZE_LIMIT=256
endif

ifeq (${CONFIG_${NAMESPACE}_DRAM_SIZE_512},y)
MAKE_ARGS += DRAM_SIZE_LIMIT=512
endif

ifeq (${CONFIG_${NAMESPACE}_DRAM_SIZE_1024},y)
MAKE_ARGS += DRAM_SIZE_LIMIT=1024
endif

ifeq (${CONFIG_${NAMESPACE}_DRAM_SIZE_2048},y)
MAKE_ARGS += DRAM_SIZE_LIMIT=2048
endif

ifeq (${CONFIG_${NAMESPACE}_BL2_CPU_FULL_SPEED},y)
MAKE_ARGS += BL2_CPU_FULL_SPEED=1
endif

ifeq (${CONFIG_${NAMESPACE}_DDR3_FREQ_2133},y)
MAKE_ARGS += DDR3_FREQ_2133=1
endif
ifeq (${CONFIG_${NAMESPACE}_DDR3_FREQ_1866},y)
MAKE_ARGS += DDR3_FREQ_1866=1
endif

ifeq (${CONFIG_${NAMESPACE}_DDR4_FREQ_3200},y)
MAKE_ARGS += DDR4_FREQ_3200=1
endif
ifeq (${CONFIG_${NAMESPACE}_DDR4_FREQ_2666},y)
MAKE_ARGS += DDR4_FREQ_2666=1
endif

ifeq (${CONFIG_${NAMESPACE}_DDR_REFRESH_INTERVAL_780},y)
MAKE_ARGS += DDR_REFRESH_INTERVAL_780=1
endif
ifeq (${CONFIG_${NAMESPACE}_DDR_REFRESH_INTERVAL_390},y)
MAKE_ARGS += DDR_REFRESH_INTERVAL_390=1
endif
ifeq (${CONFIG_${NAMESPACE}_DDR_REFRESH_INTERVAL_292},y)
MAKE_ARGS += DDR_REFRESH_INTERVAL_292=1
endif
ifeq (${CONFIG_${NAMESPACE}_DDR_REFRESH_INTERVAL_195},y)
MAKE_ARGS += DDR_REFRESH_INTERVAL_195=1
endif